'use strict';
// Repository-only development runner. Never uses an installed Tech Hub's data.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {pack}=require('./package.cjs');
(async()=>{
 const app=path.resolve(process.argv[2]),dir=fs.mkdtempSync(path.join(os.tmpdir(),'techhub-sdk-')),seed=path.join(dir,'seed');fs.mkdirSync(seed);const file=path.join(seed,'development.zip'),m=pack(app,file),bytes=fs.readFileSync(file),platform=process.platform+'-'+process.arch;
 if(!m.platforms.includes(platform)&&!m.platforms.includes('universal'))throw Error('The app does not support '+platform);
 const catalog={schemaVersion:1,apps:[{...m,packages:{[platform]:{url:'https://github.com/horner516/Tech-Hub/releases/download/development/development.zip',size:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}}}]};fs.writeFileSync(path.join(seed,'catalog.json'),JSON.stringify(catalog));
 const {createLibrary}=require('../hub/app-library.cjs'),{startHub,loadConfig}=require('../hub/server.cjs');const library=createLibrary({dir,hostVersion:require('../package.json').version});await library.seed(seed);if(!library.read(m.id))throw Error('Development package validation failed');await library.stop();const c=loadConfig(dir);c.host='127.0.0.1';c.adminPort=31900;for(const [i,s]of Object.values(c.services).entries()){s.enabled=false;s.port=31901+i;s.backendPort=31911+i;}c.services[m.id]={port:31930,backendPort:31931,enabled:true,password:null};fs.writeFileSync(path.join(dir,'config.json'),JSON.stringify(c));const hub=await startHub({dir,modular:true,advertise:false,checkUpdates:false,seedDir:seed,libraryOptions:{request:async()=>{throw Error('Development mode: online catalog disabled');}}});console.log('Development host: http://127.0.0.1:'+hub.config.adminPort+'\nTemporary settings: '+dir);for(const signal of ['SIGINT','SIGTERM'])process.once(signal,()=>hub.stop().then(()=>process.exit(0)));
})().catch(e=>{console.error(e);process.exitCode=1;});
