const $=s=>document.querySelector(s);
let selected=null,configured=null,signature='',configRevision=null,configDirty=false;
window.addEventListener('beforeunload',e=>{if(configDirty){e.preventDefault();e.returnValue='';}});
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2500);}
function render(data){
 renderNaming(data.naming);renderAdminAccess(data);$('#openLibrary').textContent=data.moduleUpdates?'Module Library · '+data.moduleUpdates+' update'+(data.moduleUpdates===1?'':'s'):'Module Library';
 $('#running').textContent=data.services.filter(s=>s.state==='running').length+' / '+data.services.length;$('#version').textContent='v'+data.version;$('#footerVersion').textContent='v'+data.version;$('#adminPort').textContent=data.adminPort;
 $('#connection').className='dot good';$('#status').textContent='Connected to Tech Hub · Status updates every 3 seconds';
 if(data.restorePending){$('#restoreNotice').textContent='Backup restored. Quit and reopen Tech Hub to apply the restored configuration.';}
 const next=JSON.stringify(data.services);if(next===signature)return;signature=next;$('#services').replaceChildren();
 $('#libraryNotice').textContent=data.services.some(s=>!s.installed)?'Open Module Library to install modules. Existing settings are retained.':'';
 for(const s of data.services.filter(s=>s.installed)){
  const card=node('article',undefined,'card '+s.id),top=node('div',undefined,'cardTop');top.append(node('span',({dsan:'DS',lux:'LX',power:'PW',netgear:'NG',record:'RM',ultrix:'RP'})[s.id]||s.name.slice(0,2).toUpperCase(),'symbol'),node('span',s.state,'badge '+s.state));card.append(top,node('h2',s.name),node('p',s.detail,'detail'));if(s.installedVersion)card.append(node('p','Module v'+s.installedVersion,'muted'));
  const toggleLabel=node('label',undefined,'serviceToggle'),toggle=node('input');toggle.type='checkbox';toggle.checked=s.enabled;toggle.setAttribute('role','switch');toggle.setAttribute('aria-label','Enable '+s.name);toggle.disabled=s.state==='stopping';const slider=node('span',undefined,'serviceSlider');slider.setAttribute('aria-hidden','true');toggleLabel.append(toggle,slider,node('span',s.enabled?'Service enabled':'Service disabled'));card.append(toggleLabel);
  toggle.onchange=async()=>{toggle.disabled=true;try{const r=await fetch('/api/enabled',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:s.id,enabled:toggle.checked})});const result=await r.json();if(!r.ok)throw Error(result.error);toast(s.name+(toggle.checked?' enabled':' turned off; settings retained'));signature='';await refresh();}catch(error){toggle.checked=s.enabled;toast(error.message);}finally{toggle.disabled=false;}};
  const port=node('div',undefined,'port');port.append(node('span','WEB INTERFACE PORT'),node('strong',s.port));card.append(port,node('p','NETWORK ACCESS','urlLabel'));
  const urls=node('div',undefined,'urls');for(const url of [...(s.hostnameURL?[s.hostnameURL]:[]),...s.urls]){const row=node('div',undefined,'url'),copy=node('button','Copy','copy');copy.setAttribute('aria-label','Copy '+s.name+' URL '+url);copy.onclick=async()=>{try{await navigator.clipboard.writeText(url);toast('Network URL copied');}catch{toast('Copy unavailable. Select and copy the URL.');}};row.append(node('code',url),copy);urls.append(row);}if(!s.urls.length)urls.append(node('p','No LAN address available','muted'));card.append(urls);if(s.hostnameStatus==='conflict')card.append(node('p','This name is already used on the network. Change this service’s hostname or the machine identifier. Use the IP link meanwhile.','error'));else if(s.hostnameStatus==='unavailable')card.append(node('p','Local hostname unavailable. Use an IP link above.','muted'));else if(s.hostnameStatus==='announcing')card.append(node('p','Announcing local hostname…','muted'));
  const access=node('div',undefined,'accessLine'),edit=node('button','Set password','textButton');edit.setAttribute('aria-label','Set password '+s.name);edit.onclick=()=>{selected=s.id;$('#accessTitle').textContent=s.name;$('#password').value='';$('#accessError').textContent='';$('#access').showModal();};access.append(node('span',s.protected?'Password required':s.urls.length?'Open on the show network':'Local access · no password'),edit);card.append(access);
  const restart=node('button','Restart service','textButton');restart.disabled=!s.enabled||['starting','recovering','stopping'].includes(s.state);restart.onclick=async()=>{restart.disabled=true;try{const r=await fetch('/api/restart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:s.id})});const result=await r.json();if(!r.ok)throw Error(result.error);toast('Restarting '+s.name);await refresh();}catch(error){toast(error.message);restart.disabled=false;}};card.append(restart);
  if(s.id==='record'){const settings=node('button','Configure','textButton');settings.onclick=async()=>{try{const r=await fetch('/api/service-config?id='+s.id);const value=await r.json();if(!r.ok)throw Error(value.error);configured=s.id;configRevision=r.headers.get('etag');configDirty=false;$('#configForm .primary').textContent='Save settings';$('#configTitle').textContent=s.name+' settings';$('#configValue').value=JSON.stringify(value,null,2);$('#configError').textContent='';$('#configHelp').textContent=s.id==='record'?'Add devices with name, type (hyperdeck or kipro), and host. Controls default to this computer; disk formatting is disabled.':'Set router.host and router.port, then define your levels and profiles. An empty host keeps the router disconnected.';$('#configuration').showModal();}catch(error){toast(error.message);}};card.append(settings);}
  if(['netgear','ultrix'].includes(s.id)){const settings=node('a',s.id==='ultrix'?'Configure routers ↗':'Configure switches ↗','textButton');settings.href=s.localURL+'/setup';settings.target='_blank';settings.rel='noreferrer';card.append(settings);}
  if(s.error)card.append(node('p',s.error,'error'));
  const open=node('a','Open dashboard ↗','open');open.href=s.localURL;open.target='_blank';open.rel='noreferrer';open.setAttribute('aria-disabled',s.state!=='running');card.append(open);$('#services').append(card);
 }
}
async function refresh(){try{const r=await fetch('/api/status');if(r.status===401||r.status===403){location.replace('/');return;}if(!r.ok)throw Error();render(await r.json());}catch{$('#connection').className='dot';$('#status').textContent='Tech Hub is disconnected. Reopen the Tech Hub app.';$('#running').textContent='—';document.querySelectorAll('.open').forEach(a=>a.setAttribute('aria-disabled','true'));signature='';}}
$('#cancel').onclick=()=>$('#access').close();
$('#accessForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected,password:$('#password').value})});const result=await r.json();if(!r.ok)throw Error(result.error);$('#access').close();toast('Service access updated');await refresh();}catch(error){$('#accessError').textContent=error.message;}finally{button.disabled=false;}};
refresh();setInterval(refresh,3000);

let updateSignature='';
function renderUpdates(data){
 const checking=data.status==='checking';$('#checkUpdates').disabled=checking;
 $('#updateStatus').textContent=checking?'Checking GitHub for updates…':data.status==='error'?data.error:data.status==='idle'?'Update check has not run yet.':data.available?`Update available: v${data.currentVersion} → v${data.latestVersion}`:`Installed: v${data.currentVersion}. No newer desktop release is available.`;
 $('#updates').classList.toggle('available',data.available);
 $('#updateDownload').textContent=data.available?`Download Tech Hub v${data.latestVersion} ↗`:'Open downloads ↗';
 const next=JSON.stringify(data.releases);if(next===updateSignature)return;updateSignature=next;
 $('#releaseNotes').replaceChildren();
 if(data.releases.length)$('#releaseNotes').append(node('h3',`What’s changed since v${data.currentVersion}`));
 for(const release of data.releases){
   const item=node('article'),heading=node('h4','Tech Hub v'+release.version),notes=node('pre',release.notes),link=node('a','View release on GitHub ↗');
   link.href=release.url;link.target='_blank';link.rel='noreferrer';item.append(heading,notes,link);$('#releaseNotes').append(item);
 }
}
async function refreshUpdates(){try{const r=await fetch('/api/updates');if(!r.ok)throw Error();renderUpdates(await r.json());}catch{$('#updateStatus').textContent='Unable to read update status. Reopen Tech Hub or try again.';$('#checkUpdates').disabled=false;}}
$('#checkUpdates').onclick=async()=>{ $('#checkUpdates').disabled=true;try{const r=await fetch('/api/updates/check',{method:'POST'});if(!r.ok)throw Error();renderUpdates(await r.json());}catch{$('#updateStatus').textContent='Unable to check for updates. Try again.';$('#checkUpdates').disabled=false;} };
refreshUpdates();setInterval(refreshUpdates,3000);

$('#configValue').oninput=()=>configDirty=true;
function discardConfig(){if(configDirty&&!confirm('Discard unsaved settings?'))return false;configDirty=false;return true;}
$('#configCancel').onclick=()=>{if(discardConfig())$('#configuration').close();};
$('#configuration').oncancel=e=>{if(!discardConfig())e.preventDefault();};
$('#configForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const value=JSON.parse($('#configValue').value);const r=await fetch('/api/service-config?id='+configured,{method:'POST',headers:{'Content-Type':'application/json',...(configRevision?{'If-Match':configRevision}:{})},body:JSON.stringify(value)});const result=await r.json();if(!r.ok)throw Error(result.error);configDirty=false;$('#configuration').close();toast('Settings saved and applied');await refresh();}catch(error){$('#configError').textContent=error.message;}finally{button.disabled=false;}};

function downloadJSON(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function apiPost(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error);return value;}
$('#openBackups').onclick=async()=>{$('#backupError').textContent='';$('#backupPassphrase').value='';$('#importBackupFile').value='';$('#backupDialog').showModal();try{const r=await fetch('/api/backup/list');if(!r.ok)throw Error('Unable to list backups');const {backups}=await r.json();$('#automaticBackup').replaceChildren(...backups.map(id=>{const o=node('option',id.replace('snapshot-','').replace('.json',''));o.value=id;return o;}));$('#restoreAutomatic').disabled=!backups.length;}catch(e){$('#backupError').textContent=e.message;}};
$('#closeBackups').onclick=()=>{$('#backupPassphrase').value='';$('#backupDialog').close();};
async function backupAction(button,fn){button.disabled=true;$('#backupError').textContent='';try{await fn();}catch(e){$('#backupError').textContent=e.message;}finally{button.disabled=false;}}
$('#exportBackup').onclick=e=>backupAction(e.currentTarget,async()=>{const result=await apiPost('/api/backup/export',{passphrase:$('#backupPassphrase').value});downloadJSON('Tech-Hub-backup-'+new Date().toISOString().slice(0,10)+'.json',result);});
async function restoreBackup(body){if(!confirm('Restore this backup and stop all services? Current settings will be backed up. You must quit and reopen Tech Hub afterward.'))return;const result=await apiPost('/api/backup/restore',body);$('#backupPassphrase').value='';$('#backupDialog').close();$('#restoreNotice').textContent=result.message;await refresh();}
$('#importBackup').onclick=e=>backupAction(e.currentTarget,async()=>{const file=$('#importBackupFile').files[0];if(!file)throw Error('Choose a backup file');if(file.size>16*1024*1024)throw Error('Backup file is too large');await restoreBackup({backup:JSON.parse(await file.text()),passphrase:$('#backupPassphrase').value});});
$('#restoreAutomatic').onclick=e=>backupAction(e.currentTarget,()=>restoreBackup({snapshot:$('#automaticBackup').value}));
let diagnosticReport;
async function showDiagnostics(){const target=$('#diagnosticResults');target.textContent='Reading service status…';$('#downloadDiagnostics').disabled=true;try{const r=await fetch('/api/diagnostics',{signal:AbortSignal.timeout(6000)});if(!r.ok)throw Error('Unable to read diagnostics');diagnosticReport=await r.json();target.replaceChildren();for(const service of diagnosticReport.services){const item=node('section');item.append(node('h3',service.name+' · '+service.state),node('p','Web port '+service.webPort+' · Last status check: '+(service.lastSuccessfulCheck?new Date(service.lastSuccessfulCheck).toLocaleString():'Not available')));if(service.problem)item.append(node('p',service.problem,'error'));for(const d of service.devices)item.append(node('p','Device '+d.device+': '+d.status+' · Last data: '+(d.lastSuccessfulUpdate?new Date(d.lastSuccessfulUpdate).toLocaleString():'Not available')+(d.problem?' · '+d.problem:'')));target.append(item);}target.append(node('h3','Recent service events'));if(!diagnosticReport.recentEvents.length)target.append(node('p','No service events recorded in this session.'));for(const e of diagnosticReport.recentEvents)target.append(node('p',new Date(e.time).toLocaleTimeString()+' · '+e.service+' · '+e.state+' · '+e.summary));$('#downloadDiagnostics').disabled=false;}catch(e){target.textContent=e.message;}}
$('#openDiagnostics').onclick=()=>{$('#diagnosticsDialog').showModal();showDiagnostics();};$('#refreshDiagnostics').onclick=showDiagnostics;$('#closeDiagnostics').onclick=()=>$('#diagnosticsDialog').close();$('#downloadDiagnostics').onclick=()=>{if(diagnosticReport)downloadJSON('Tech-Hub-diagnostics.json',diagnosticReport);};

let namingInitialized=false,namingDirty=false;
const namingServices={master:['Tech Hub directory','tech'],dsan:['D’san Ready','dsan'],power:['Power Monitor','pd'],netgear:['NETGEAR AV Switchboard','netgear'],record:['Record Monitor','record'],ultrix:['Router Panel','router']};
function readServiceNames(){return Object.fromEntries(Object.keys(namingServices).map(id=>[id,$('#hostname-'+id).value]));}
for(const [id,[label,defaultName]] of Object.entries(namingServices)){const field=node('label',label),input=node('input');input.id='hostname-'+id;input.value=defaultName+'.local';input.required=true;input.maxLength=69;input.autocomplete='off';input.setAttribute('autocapitalize','none');input.spellcheck=false;input.oninput=()=>{namingDirty=true;previewNaming();};field.append(input);$('#serviceNames').append(field);}
function previewNaming(){const suffix=$('#machineSuffix').value.trim().toLowerCase();$('#namingPreview').textContent=Object.values(readServiceNames()).map(n=>n.trim().toLowerCase().replace(/\.local$/,'')+(suffix?'-'+suffix:'')+'.local').join(' · ');}
function renderNaming(value){if(!value)return;for(const [id,name]of Object.entries(value.names||{}))if(id!=='lux'&&!namingServices[id]){namingServices[id]=[id,name];const field=node('label',id),input=node('input');input.id='hostname-'+id;input.value=name+'.local';input.required=true;input.maxLength=69;input.autocomplete='off';input.oninput=()=>{namingDirty=true;previewNaming();};field.append(input);$('#serviceNames').append(field);}if(!namingInitialized||!namingDirty){$('#machineSuffix').value=value.suffix;$('#portless').checked=value.portless;for(const [id,[,fallback]] of Object.entries(namingServices))$('#hostname-'+id).value=(value.names?.[id]||fallback)+'.local';namingInitialized=true;previewNaming();}const status=$('#namingStatus');status.replaceChildren();status.append(node('span',value.portless?(value.available?'Addresses without port numbers are available. ':value.error||'Network names are available when Tech Hub is serving the local network.'):'Addresses use each service’s assigned port. '));if(value.directory?.hostnameURL){const link=node('a','Open '+value.directory.hostname);link.href=value.directory.hostnameURL;link.target='_blank';link.rel='noreferrer';status.append(link);}else if(value.directory?.hostnameStatus==='conflict')status.append(node('span','The Tech Hub directory name is already in use. Choose a different identifier.'));}
$('#machineSuffix').oninput=()=>{namingDirty=true;previewNaming();};$('#portless').onchange=()=>namingDirty=true;
$('#namingForm').onsubmit=async e=>{e.preventDefault();$('#saveNaming').disabled=true;$('#namingError').textContent='';try{await apiPost('/api/naming',{suffix:$('#machineSuffix').value,portless:$('#portless').checked,names:readServiceNames()});namingDirty=false;toast('Network names saved. Reopen shared pages using the updated links.');await refresh();}catch(error){$('#namingError').textContent=error.message;}finally{$('#saveNaming').disabled=false;}};

let adminAccessDirty=false,latestAdminStatus=null;
function renderAdminAccess(data){latestAdminStatus=data;$('#logoutForm').hidden=data.localAdmin;if(!adminAccessDirty){$('#remoteAdminEnabled').checked=data.remoteAdmin.enabled;$('#adminPasswordFields').hidden=!data.remoteAdmin.enabled;}$('#adminAccessStatus').textContent=data.remoteAdmin.enabled?'Remote administration enabled. Password changes sign out network administrators.':'Administration is restricted to this computer.';$('#adminAccessURLs').replaceChildren();if(data.remoteAdmin.enabled)for(const url of data.remoteAdmin.urls)$('#adminAccessURLs').append(node('p',url));}
$('#openSettings').onclick=()=>{$('#settingsDialog').showModal();};
function closeSettings(){if((namingDirty||adminAccessDirty)&&!confirm('Discard unsaved settings?'))return false;namingDirty=false;adminAccessDirty=false;$('#adminPassword').value='';$('#settingsDialog').close();if(latestAdminStatus){renderNaming(latestAdminStatus.naming);renderAdminAccess(latestAdminStatus);}return true;}
$('#closeSettings').onclick=closeSettings;$('#settingsDialog').oncancel=e=>{e.preventDefault();closeSettings();};
$('#remoteAdminEnabled').onchange=()=>{adminAccessDirty=true;$('#adminPasswordFields').hidden=!$('#remoteAdminEnabled').checked;};$('#adminPassword').oninput=()=>adminAccessDirty=true;
$('#adminAccessForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('#adminAccessError').textContent='';try{await apiPost('/api/admin-access',{enabled:$('#remoteAdminEnabled').checked,password:$('#adminPassword').value});adminAccessDirty=false;$('#adminPassword').value='';toast('Administration access saved');await refresh();}catch(error){$('#adminAccessError').textContent=error.message;}finally{button.disabled=false;}};
async function refreshDevices(){if(!$('#devicesDialog').open)return;try{const r=await fetch('/api/viewers');if(!r.ok)throw Error('Unable to read connected devices.');const {viewers}=await r.json();$('#devicesSummary').textContent=`${new Set(viewers.map(v=>v.ip)).size} client IPs · ${viewers.reduce((n,v)=>n+v.sessions,0)} active page sessions`;$('#deviceRows').replaceChildren();for(const viewer of viewers){const row=node('article',undefined,'deviceRow');row.append(node('code',viewer.ip),node('span',viewer.service==='master'?'Tech Hub administration':namingServices[viewer.service]?.[0]||viewer.service),node('span',`${viewer.sessions} page${viewer.sessions===1?'':'s'} · ${Math.max(0,Math.floor((Date.now()-viewer.lastSeen)/1000))}s ago`));$('#deviceRows').append(row);}if(!viewers.length)$('#deviceRows').append(node('p','No active browser pages.'));}catch(error){$('#devicesSummary').textContent=error.message;}}
$('#openDevices').onclick=()=>{$('#devicesDialog').showModal();refreshDevices();};$('#closeDevices').onclick=()=>$('#devicesDialog').close();setInterval(refreshDevices,3000);
window.addEventListener('beforeunload',e=>{if(namingDirty||adminAccessDirty){e.preventDefault();e.returnValue='';}});

let libraryState=null,librarySignature='',librarySelection=new Set();
async function refreshLibrary(){
 try{
  const r=await fetch('/api/apps');if(!r.ok)throw Error('Unable to read Module Library');
  const data=await r.json();libraryState=data;
  const updateText=data.updateCount?`${data.updateCount} module update${data.updateCount===1?'':'s'} available`:'No module updates in the current catalog';
  $('#libraryStatus').textContent=data.busy?'Installing or changing modules… Keep Tech Hub open.':data.refreshing?'Checking for module updates…':data.error?`Update check failed: ${data.error}. Showing the saved catalog.`:`${updateText}. ${data.checkedAt?'Last checked '+new Date(data.checkedAt).toLocaleString(): 'Check for updates to refresh the catalog.'}`;
  for(const id of ['refreshLibrary','installSelected','installAll','installPrevious','importApps','reviewLocalApp'])$('#'+id).disabled=!!data.busy||!!data.refreshing;
  $('#updateAll').disabled=!!data.busy||!!data.refreshing||!data.readyUpdateCount;
  $('#updateAll').textContent=data.readyUpdateCount?`Update all (${data.readyUpdateCount})`:'Update all';
  $('#installPrevious').hidden=!data.recommended?.some(id=>data.apps.some(a=>a.id===id&&!a.installedVersion));
  const sig=JSON.stringify(data);if(sig===librarySignature)return;librarySignature=sig;$('#libraryApps').replaceChildren();
  for(const a of data.apps){
   const card=node('article',undefined,'libraryCard'),label=node('label',undefined,'librarySelect'),choice=node('input');
   choice.type='checkbox';choice.checked=librarySelection.has(a.id);choice.disabled=!a.compatible||data.busy||a.unofficial||a.unlisted;choice.onchange=()=>choice.checked?librarySelection.add(a.id):librarySelection.delete(a.id);
   label.append(choice,node('strong',a.name));card.append(label,node('p',a.unofficial?'Unofficial · locally installed':'Official catalog','badge'),node('p',a.description));
   card.append(node('p',a.installedVersion?'Installed: v'+a.installedVersion:'Not installed'));
   if(a.unofficial)card.append(node('p','Updates: import a newer package from its developer.','muted'));
   else if(a.unlisted)card.append(node('p','Not listed in the current catalog.','muted'));
   else card.append(node('p','Catalog: v'+a.version+(a.updateAvailable?' · Update available':a.installedVersion===a.version?' · Up to date':'')));
   if(!a.compatible&&!a.unofficial&&!a.unlisted)card.append(node('p','Installing this version requires a supported platform and Tech Hub '+a.minHostVersion+' or later.','error'));
   if(a.permissions.length)card.append(node('p','Access: '+a.permissions.join(', '),'muted'));
   if(a.job)card.append(node('p',a.job.error||a.job.state+(a.job.progress===undefined?'':' · '+a.job.progress+'%'),a.job.error?'error':'muted'));
   if(a.installedVersion&&!data.loaded?.includes(a.id))card.append(node('p','Quit and reopen Tech Hub to load this new module.','muted'));
   const actions=node('div',undefined,'actions');
   for(const [action,title,show]of [['install',a.installedVersion?'Update':'Install',!a.unofficial&&!a.unlisted&&(!a.installedVersion||a.updateAvailable)],['rollback','Roll back',a.rollback],['uninstall','Uninstall',a.installedVersion]])if(show){const b=node('button',title);b.disabled=data.busy||data.refreshing||(action==='install'&&!a.compatible);b.onclick=()=>appAction([a.id],action);actions.append(b);}
   card.append(actions);$('#libraryApps').append(card);
  }
  if(!data.apps.length)$('#libraryApps').append(node('p','No catalog is available yet. Connect to the internet and check for updates, or install Tech Hub Full.'));
 }catch(e){$('#libraryStatus').textContent=e.message;}
}
async function appAction(ids,action='install'){if(!ids.length){$('#libraryError').textContent='Select at least one compatible module.';return;}if(action==='uninstall'&&!confirm('Uninstall the selected module? Its saved settings will be retained.'))return;$('#libraryError').textContent='';try{await apiPost('/api/apps/action',{ids,action});await refreshLibrary();await refresh();}catch(e){$('#libraryError').textContent=e.message;}}
$('#openLibrary').onclick=()=>{$('#libraryDialog').showModal();refreshLibrary();};$('#closeLibrary').onclick=()=>$('#libraryDialog').close();$('#refreshLibrary').onclick=async()=>{try{await apiPost('/api/apps/refresh',{});await refreshLibrary();}catch(e){$('#libraryError').textContent=e.message;}};
$('#updateAll').onclick=()=>appAction((libraryState?.apps||[]).filter(a=>a.canUpdate&&!a.unofficial).map(a=>a.id));
$('#installSelected').onclick=()=>appAction([...librarySelection].filter(id=>libraryState?.apps.some(a=>a.id===id&&!a.unlisted&&!a.unofficial&&a.compatible)));$('#installAll').onclick=()=>appAction((libraryState?.apps||[]).filter(a=>a.compatible&&!a.unlisted&&!a.unofficial).map(a=>a.id));$('#installPrevious').onclick=()=>appAction((libraryState?.recommended||[]).filter(id=>libraryState.apps.some(a=>a.id===id&&a.compatible)));
$('#importApps').onclick=async()=>{const file=$('#offlineBundle').files[0];if(!file){$('#libraryError').textContent='Choose an all-modules ZIP file.';return;}if(file.size>512*1024*1024){$('#libraryError').textContent='Bundle exceeds 512 MB.';return;}$('#importApps').disabled=true;$('#libraryError').textContent='';try{const r=await fetch('/api/apps/import',{method:'POST',headers:{'Content-Type':'application/zip'},body:file});const result=await r.json();if(!r.ok)throw Error(result.error);await refreshLibrary();await refresh();}catch(e){$('#libraryError').textContent=e.message;}finally{$('#importApps').disabled=false;}};
setInterval(()=>{if($('#libraryDialog').open)refreshLibrary();},2000);

let localAppReview=null;
$('#reviewLocalApp').onclick=async()=>{const file=$('#localAppFile').files[0];$('#libraryError').textContent='';if(!file){$('#libraryError').textContent='Choose a local module ZIP package.';return;}if(file.size>256*1024*1024){$('#libraryError').textContent='Module package exceeds 256 MB.';return;}$('#reviewLocalApp').disabled=true;try{const r=await fetch('/api/apps/local/inspect',{method:'POST',headers:{'Content-Type':'application/zip'},body:file});const value=await r.json();if(!r.ok)throw Error(value.error);localAppReview=value;const m=value.manifest;$('#localAppDetails').replaceChildren(node('h3',m.name+' · v'+m.version),node('p',m.description),node('p','Module ID: '+m.id),node('p','Declared access: '+(m.permissions.join(', ')||'none')),node('p',value.replacing?'Replaces the installed test version. Settings are retained and the previous version is kept for rollback.':'Quit and reopen Tech Hub after installation to load this new module.'),node('p','SHA-256: '+value.sha256,'packageHash'));$('#trustLocalApp').checked=false;$('#confirmLocalApp').disabled=true;$('#localAppError').textContent='';$('#localAppReview').showModal();}catch(e){$('#libraryError').textContent=e.message;}finally{$('#reviewLocalApp').disabled=false;}};
$('#trustLocalApp').onchange=()=>$('#confirmLocalApp').disabled=!$('#trustLocalApp').checked;
function cancelLocalReview(){if(localAppReview)void apiPost('/api/apps/local/cancel',{token:localAppReview.token}).catch(()=>{});$('#localAppReview').close();localAppReview=null;}
$('#cancelLocalApp').onclick=cancelLocalReview;$('#localAppReview').oncancel=e=>{e.preventDefault();cancelLocalReview();};
$('#confirmLocalApp').onclick=async()=>{if(!localAppReview||!$('#trustLocalApp').checked)return;$('#confirmLocalApp').disabled=true;try{await apiPost('/api/apps/local/install',{token:localAppReview.token,confirm:true});localAppReview=null;$('#localAppReview').close();$('#localAppFile').value='';toast('Unofficial module installed. Check Module Library for restart instructions.');await refreshLibrary();await refresh();}catch(e){$('#localAppError').textContent=e.message;}finally{$('#confirmLocalApp').disabled=!$('#trustLocalApp').checked;}};
