'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{promisify}=require('node:util');
const files=['config.json','dsan/viewer-config.json','lux/devices.json','power/settings.json','netgear/.env','netgear/color-scheme.json','record/config.json','ultrix/config.json'];
function collect(dir){const data={};for(const name of files){const file=path.join(dir,name);if(fs.existsSync(file)){if(fs.lstatSync(file).isSymbolicLink()||fs.statSync(file).size>2*1024*1024)throw Error('Unsupported configuration file: '+name);data[name]=fs.readFileSync(file,'utf8');}}if(Buffer.byteLength(JSON.stringify(data))>8*1024*1024)throw Error('Configuration backup exceeds the 8 MB limit');return {format:'tech-hub-config',version:1,createdAt:new Date().toISOString(),files:data};}
function snapshot(dir){const data=collect(dir),folder=path.join(dir,'backups');fs.mkdirSync(folder,{recursive:true,mode:0o700});const existing=fs.readdirSync(folder).filter(f=>/^snapshot-.*\.json$/.test(f)).sort();if(existing.length){const previous=JSON.parse(fs.readFileSync(path.join(folder,existing.at(-1)),'utf8'));if(JSON.stringify(previous.files)===JSON.stringify(data.files))return existing.at(-1);}const name='snapshot-'+new Date().toISOString().replace(/[:.]/g,'-')+'-'+crypto.randomBytes(3).toString('hex')+'.json';fs.writeFileSync(path.join(folder,name),JSON.stringify(data),{mode:0o600});for(const old of existing.slice(0,Math.max(0,existing.length-9)))fs.unlinkSync(path.join(folder,old));return name;}
function validate(data,validateService){if(data?.format!=='tech-hub-config'||data.version!==1||!data.files||typeof data.files!=='object'||Array.isArray(data.files))throw Error('Invalid backup');if(!Object.hasOwn(data.files,'config.json'))throw Error('Backup has no Tech Hub configuration');for(const [name,value]of Object.entries(data.files)){if(!files.includes(name)||typeof value!=='string'||Buffer.byteLength(value)>2*1024*1024)throw Error('Unsupported backup entry');if(name.endsWith('.json')){const parsed=JSON.parse(value);if(!parsed||typeof parsed!=='object')throw Error('Invalid configuration JSON');if(name==='record/config.json')validateService('record',parsed);if(name==='ultrix/config.json')validateService('ultrix',parsed);}}return data;}
async function key(password,salt){if(typeof password!=='string'||password.length<12||password.length>1024)throw Error('Use a backup passphrase of 12–1024 characters');return promisify(crypto.scrypt)(password,salt,32);}
async function seal(data,password){const salt=crypto.randomBytes(16),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',await key(password,salt),iv);const bytes=Buffer.concat([cipher.update(JSON.stringify(data),'utf8'),cipher.final()]);return {format:'tech-hub-encrypted-backup',version:1,salt:salt.toString('base64'),iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:bytes.toString('base64')};}
async function open(envelope,password){if(envelope?.format!=='tech-hub-encrypted-backup'||envelope.version!==1||typeof envelope.data!=='string'||envelope.data.length>16*1024*1024)throw Error('Invalid encrypted backup');try{const salt=Buffer.from(envelope.salt,'base64'),iv=Buffer.from(envelope.iv,'base64'),tag=Buffer.from(envelope.tag,'base64');if(salt.length!==16||iv.length!==12||tag.length!==16)throw Error();const decipher=crypto.createDecipheriv('aes-256-gcm',await key(password,salt),iv);decipher.setAuthTag(tag);return JSON.parse(Buffer.concat([decipher.update(Buffer.from(envelope.data,'base64')),decipher.final()]).toString('utf8'));}catch{throw Error('Unable to unlock backup. Check the passphrase and file.');}}
function restore(dir,data){const previous=collect(dir);function apply(bundle){for(const name of files){const dest=path.join(dir,name);fs.mkdirSync(path.dirname(dest),{recursive:true,mode:0o700});if(fs.existsSync(dest)&&fs.lstatSync(dest).isSymbolicLink())throw Error('Cannot restore over a symbolic link');if(Object.hasOwn(bundle.files,name)){fs.writeFileSync(dest+'.restore',bundle.files[name],{mode:0o600});fs.renameSync(dest+'.restore',dest);}else if(fs.existsSync(dest))fs.unlinkSync(dest);}}try{apply(data);}catch(error){apply(previous);throw error;}}
function list(dir){const folder=path.join(dir,'backups');return fs.existsSync(folder)?fs.readdirSync(folder).filter(f=>/^snapshot-[0-9TZ-]+-[a-f0-9]{6}\.json$/.test(f)).sort().reverse():[];}
function saved(dir,id){if(!list(dir).includes(id))throw Error('Unknown automatic backup');return JSON.parse(fs.readFileSync(path.join(dir,'backups',id),'utf8'));}
module.exports={files,collect,snapshot,validate,seal,open,restore,list,saved};
