window.TechHubUltrixEditor=function(container,config){
 const make=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 const readers=[];
 function field(parent,label,value,type='text'){const l=make('label',label),i=make('input');i.type=type;if(type==='checkbox'){l.className='check';i.checked=!!value;}else i.value=value??'';l.append(i);parent.append(l);return i;}
 function section(title){const d=make('details');d.open=true;d.append(make('summary',title));container.append(d);return d;}
 function rows(parent,values,build,addLabel){const list=make('div');parent.append(list);let entries=[];function add(value){const box=make('section');box.className='device';const fields=make('div');fields.className='fields';box.append(fields);const read=build(fields,value),remove=make('button','Remove');remove.type='button';const e={read};remove.onclick=()=>{entries=entries.filter(x=>x!==e);box.remove();};box.append(remove);list.append(box);entries.push(e);}values.forEach(add);const button=make('button',addLabel);button.type='button';button.onclick=()=>add({});parent.append(button);return()=>entries.map(e=>e.read());}
 const levels=section('Levels');levels.append(make('p','Level order is its router number, starting at 1. Update profile level numbers if you remove a level.'));
 const getLevels=rows(levels,config.levels,(p,v)=>{const name=field(p,'Level name',v.name),short=field(p,'Abbreviation',v.short);return()=>({...v,name:name.value,short:short.value||name.value});},'Add level');readers.push(()=>config.levels=getLevels());
 for(const kind of ['sources','destinations']){
  const existing=config[kind]||{},part=section(kind==='sources'?'Sources':'Destinations'),fields=make('div');fields.className='fields';part.append(fields);
  const count=field(fields,'Known count (0 = learn from router)',existing.count??0,'number');count.min='0';count.max='65535';
  const include=field(fields,'Include numbers (blank = all)',existing.include),hidden=field(fields,'Hidden numbers',existing.hidden),protectedInput=kind==='destinations'?field(fields,'Protected destinations',existing.protected):null;
  const hideUnnamed=field(fields,'Hide unnamed entries',existing.hideUnnamed,'checkbox');
  part.append(make('p','Use ranges such as 1-16,20. Labels below override router names. Existing category rules are retained.'));
  const getLabels=rows(part,Object.entries(existing.labels||{}).map(([number,name])=>({number,name})),(p,v)=>{const number=field(p,'Router number',v.number,'number'),name=field(p,'Display name',v.name);number.min='1';number.max='65535';return()=>({number:Number(number.value),name:name.value});},'Add label');
  readers.push(()=>{const labels={};for(const row of getLabels()){if(Object.hasOwn(labels,row.number))throw Error('Duplicate '+kind+' label number');labels[row.number]=row.name;}const s={...existing,count:Number(count.value),hideUnnamed:hideUnnamed.checked,labels};for(const [k,input]of [['include',include],['hidden',hidden],['protected',protectedInput]])if(input){if(input.value.trim())s[k]=input.value.trim();else delete s[k];}config[kind]=s;});
 }
 const profiles=section('Access profiles'),defaultInput=field(profiles,'Default profile ID',config.defaultProfile);
 profiles.append(make('p','Profile IDs must be unique. Level numbers are comma-separated; blank allows all levels. Changing access settings signs viewers out.'));
 const getProfiles=rows(profiles,Object.entries(config.profiles).map(([id,p])=>({id,...p})),(parent,v)=>{const id=field(parent,'Profile ID',v.id),title=field(parent,'Display name',v.title||v.label||v.id),readOnly=field(parent,'Read only',v.readOnly,'checkbox'),pin=field(parent,'PIN (blank = no PIN)',v.pin,'password'),levels=field(parent,'Allowed level numbers',v.levels?.join(','));pin.autocomplete='new-password';const src=field(parent,'Visible source numbers (blank = all)',v.sources?.include),dst=field(parent,'Visible destination numbers (blank = all)',v.destinations?.include);return()=>{const {id:unused,...old}=v;const p={...old,title:title.value,readOnly:readOnly.checked,pin:pin.value};if(levels.value.trim())p.levels=levels.value.split(',').map(x=>Number(x.trim()));else delete p.levels;for(const [k,input]of [['sources',src],['destinations',dst]]){p[k]={...p[k]};if(input.value.trim())p[k].include=input.value.trim();else delete p[k].include;}return {id:id.value.trim(),value:p};};},'Add profile');
 readers.push(()=>{const profiles=Object.create(null);for(const p of getProfiles()){if(Object.hasOwn(profiles,p.id))throw Error('Duplicate profile ID');profiles[p.id]=p.value;}config.profiles=profiles;config.defaultProfile=defaultInput.value.trim();});
 return ()=>{for(const read of readers)read();};
};
